### ISSUE TITLE
Session lost

### ISSUE THREAD

**Issue by rubenluz** [mmzdouc/FERMO#23]
I am trying to use FERMO with a big dataset (after filtering ~7700). As it is taking a long time to process I am losing the session for some reason, and after finishing I can not see the end results. 

So I have two suggestions:

-Automatically save the JSON file so that even if the frontend fails the results can be retrieved;
-Notify in the console that it had finished and where is the JSON file;
-MPI? It took a long time to process, and i saw it was using just one core, is it optional?

I tried both in windows and linux, in linux I lost the session in the front end several times.

Rúben

**Comment by mmzdouc** [comment]
Hi Rúben, 

thank you for opening this issue and for your suggestions! 

We are aware of the performance limitations of FERMO and have also observed the timeouts with larger datasets. We suspect the timeouts come from the Plotly Dash framework which we are currently using for the frontend. Plotly Dash also prevents us to use multiprocessing - all attempts to implement it failed. 

We are currently working on replacing Plotly Dash with Flask and on implementing a better job queue, which should lead to more stable performance and allow multiprocessing. We hope to finish the rework by January. I will leave this issue open and notify you once we have the new system running!

Kind regards, Mitja

**Comment by elnurgar** [comment]
Hi,

I am also trying to use Fermo on a very large dataset with 19000 features on neg mode and 12000 features on pos mode.

After `2024-06-02 00:31:44.382168: Completed: "determine_bioactive_features.py": QuantData factor : 10;` I get error on the webpage as it can not be shown out of memory.

It is strange as the PC has 128 Gb Ram.

Thank you in advance,
With best regards,
Elnur

**Comment by mmzdouc** [comment]
Not applicable in version >=1.0.0
