### ISSUE TITLE
No import of csv file

### ISSUE THREAD

**Issue by elnurgar** [mmzdouc/FERMO#26]
Hi,

I am trying to import a very big csv file with 19000 features which weights about 189 Mb. The mgf file is uploaded without any problems, however nothing happens when I am trying to charge csv file.

Do you have any idea where to search for a problem?

Thank you very much,
Elnur

**Comment by mmzdouc** [comment]
Hello Elnur, 

thank you for your interest in FERMO!

I assume that you are running FERMO version `0.8.12`? Unfortunately, file sizes like in your case exceed the scope of this version  by far! I have never tested it with files beyond 10 MB, and I assume that the GUI simply times out and crashes. 

However, we are currently developing a new version of FERMO, which should in theory be able to also run large analyses like yours. It comes in two parts: the command line version `fermo_core` is already available and can be used on Linux machines  (see http://github.com/mmzdouc/fermo_core). The graphical user interface version `fermo_gui` is still under development, but we are planning to relase it in a few weeks (will be made availble on https://github.com/mmzdouc/FERMO). Similar to the previous version of FERMO, the GUI will be made available as offline tool. There will also be an online version, but this version will have restrictions in calculation time, so it is probably not suitable for your needs. 

Kind regards, 

Mitja
